apiVersion: v1
kind: Service
metadata:
  name: fluxdeploy-api
  namespace: fluxdeploy-dev
  labels:
    app: fluxdeploy-api
spec:
  type: ClusterIP
  selector:
    app: fluxdeploy-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000