apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluxdeploy-staging

resources:
  - ../../base/configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/hpa.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: fluxdeploy-staging
      - op: replace
        path: /data/APP_ENV
        value: "staging"
    target:
      kind: ConfigMap
      name: fluxdeploy-config