apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluxdeploy-staging

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "staging"
    target:
      kind: ConfigMap
      name: fluxdeploy-config